sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      compiler: g++
      env:
        - COMPILER=g++-5
        - COVERAGE=yes
    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++
        - COVERAGE=no

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - g++-5
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-dev
      - python-pip

install:
 - if [ "$COVERAGE" = "yes" ]; then
     pip install --user cpp-coveralls;
   fi

script:
 - if [ "$COVERAGE" = "yes" ]; then
     make -j4 CXX="$COMPILER" with-coverage;
   fi

after_success:
 - if [ "$COVERAGE" = "yes" ]; then
     coveralls --encoding iso-8859-1 --exclude tests --gcov-options '\-p';
   fi

notifications:
  email:
    recipients:
      - xaizek@openmailbox.org

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache
